[workspace]
channels = ["conda-forge"]
name = "canopy-quality-repo"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.7,<3.15"
pandas = ">=3.0.5,<4"
numpy = ">=2.5.3,<3"
statsmodels = ">=0.15.0,<0.16"
geopandas = ">=1.1.4,<2"
rasterio = ">=1.5.1,<2"
seaborn = ">=0.13.2,<0.14"
matplotlib = ">=3.11.1,<4"
scipy = ">=1.18.0,<2"
earthengine-api = ">=1.7.42,<2"
